name: Publish Package to npmjs

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: npm install --global npm@11.15.0
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm publish --access public
